---
- name: "mariadb | enable slowlog"
  lineinfile:
    path: "{{ mariadb_server_config_file }}"
    insertafter: ^# Enable the slow query
    line: 'slow_query_log = 1'
  notify: restart mariadb

- name: "mariabdb | slowlog configuration"
  lineinfile:
    path: "{{ mariadb_server_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#slow_query_log_file', line: 'slow_query_log_file = /var/log/mysql/mariadb-slow.log' }
    - { regexp: '^#long_query_time', line: 'long_query_time = 10' }
    - { regexp: '^#log_slow_rate_limit', line: 'log_slow_rate_limit = 1000' }
    - { regexp: '^#log_slow_verbosity', line: 'log_slow_verbosity = query_plan' }
  notify: restart mariadb
