---
- name: "munin | create sql account"
  mysql_user:
    name: "{{ munin_sql_user }}"
    password: "{{ munin_sql_password }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT'
    state: present
    login_unix_socket: "{{ mysql_socket }}"
    login_user: root

- name: "munin | insert account details"
  template:
    src: templates/munin-mariadb.j2
    dest: "{{ munin_sql_config_file }}"
  notify: restart munin-node

- name: "munin | enable mysql plugin"
  shell: munin-node-configure --shell | grep mysql_ | sh
  args:
    creates: "{{ munin_sql_config_file }}"
  # ignore faulty munin plugins
  ignore_errors: yes
  notify: restart munin-node
