firewall: true
firewall_rules:
  # public webserver
  - "allow in to any port 443"
  - "allow in to any port 80"
  # monitoring
  - "allow in proto tcp from {{ munin_server_ip }} to any port 4949"
  # smtp
  - "allow in to any port 25"
  # ssh
  - "allow in proto tcp to any port {{ ssh_port }}"
