---
- name: reload monit
  service:
    name: monit
    state: reloaded

- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart sharedlists_web
  service:
    name: "{{ sharedlists_web_service }}"
    state: restarted

- name: restart sharedlists_smtp
  service:
    name: "{{ sharedlists_smtp_service }}"
    state: restarted

- name: restart sharedlists_web_socket
  service:
    name: "{{ sharedlists_web_socket }}"
    state: restarted
