---
- name: reload monit
  service:
    name: monit
    state: reloaded

- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart sharedlists_web
  systemd:
    name: "{{ sharedlists_web_service }}"
    daemon_reload: true
    state: restarted

- name: restart sharedlists_smtp
  systemd:
    name: "{{ sharedlists_smtp_service }}"
    daemon_reload: true
    state: restarted

- name: restart sharedlists_web_socket
  systemd:
    name: "{{ sharedlists_web_socket }}"
    daemon_reload: true
    state: restarted
