---
- name: "Changetrack | Copy default configuration"
  ansible.builtin.template:
    src: changetrack.conf
    dest: /etc/default/changetrack
    mode: 0644

- name: "Changetrack | Copy configuration"
  ansible.builtin.copy:
    src: changetrack.conf
    dest: /etc/changetrack.conf
    mode: 0644
