---
- name: "Monit | Copy configuration"
  ansible.builtin.template:
    src: monit/monitrc
    dest: /etc/monit/monitrc
    mode: "0700"
  notify: restart monit

- name: "Monit | Copy monitoring files"
  ansible.builtin.copy:
    src: "monit/conf-available/{{ item }}"
    dest: /etc/monit/conf-available/
    mode: "0600"
  loop:
    - fail2ban
    - oomkiller
  notify: restart monit

- name: "Monit | Link monitoring files"
  ansible.builtin.file:
    src: "/etc/monit/conf-available/{{ item }}"
    dest: "/etc/monit/conf-enabled/{{ item }}"
    state: link
  loop:
    - fail2ban
    - oomkiller
  notify: restart monit

- name: "Monit | Copy monitoring templates"
  ansible.builtin.template:
    src: "monit/conf-available/{{ item }}"
    dest: "/etc/monit/conf-enabled/{{ item }}"
    mode: "0644"
  loop:
    - filesystem
    - ssh
    - system
  notify: restart monit
