---
- name: "Packages | Get list of installed packages"
  ansible.builtin.package_facts:
    manager: apt

- name: "Packages | Add Debian backports repository"
  ansible.builtin.apt_repository:
    repo: "deb http://ftp.de.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free"
    state: present

- name: "Packages | Install packages"
  ansible.builtin.apt:
    pkg:
      - changetrack
      - curl
      - dehydrated
      - fail2ban
      - git
      - htop
      - locales
      - mc
      - molly-guard
      - monit
      - moreutils
      - munin-node
      - ncdu
      - rsync
      - screen
      - sqlite3
      - sudo
      - unattended-upgrades
      - vim
      - wget
    cache_valid_time: 3600

- name: "Packages | Install ferm"
  ansible.builtin.apt:
    pkg:
      - ferm
  when: ferm.install is defined and ferm.install
