---
- name: "rsnapshot | check facts"
  package_facts:
    manager: apt

- name: "rsnapshot | install packages"
  apt:
    pkg:
      - haveged
      - liblchown-perl
      - rsnapshot
  when: backup_host is defined and backup_host

- name: "rsnapshot | create ssh keys"
  command:
    cmd: ssh-keygen -a 100 -t ed25519 -N '' -f "{{ rsnapshot_ssh_key_file }}"
    creates: "{{ rsnapshot_ssh_key_file }}"
  when: backup_host is defined and backup_host

- name: "rsnapshot | create configuration directory"
  file:
    path: /etc/rsnapshot.d
    state: directory
  when: backup_host is defined and backup_host

- name: "rsnapshot | copy configuration files"
  copy:
    src: "rsnapshot/{{ item }}"
    dest: "/etc/rsnapshot.d/{{ item }}"
  loop:
    - exclude.inc
  when: backup_host is defined and backup_host

- name: "rsnapshot | copy logssh"
  copy:
    src: rsnapshot/logssh.sh
    dest: /usr/local/bin/logssh.sh
    mode: 0666
  when: backup_guest is defined and backup_guest

- name: "rsnapshot | copy cron file"
  copy:
    src: rsnapshot/cron
    dest: /etc/cron.d/rsnapshot
  when: backup_host is defined and backup_host
