---
- name: "rsnapshot | check facts"
  package_facts:
    manager: apt

- name: "rsnapshot | install packages"
  apt:
    pkg:
      - haveged
      - liblchown-perl

# Get by download as the package is only in unstable
- name: "rsnapshot | get deb package"
  get_url:
    url: "{{ rsnapshot_deb_url }}"
    dest: /tmp/rsnapshot.deb
  when: "'rsnapshot' not in ansible_facts.packages"

- name: "rsnapshot | install package"
  command: dpkg -i /tmp/rsnapshot.deb
  when: "'rsnapshot' not in ansible_facts.packages"

- name: "rsnapshot | create ssh keys"
  command:
    cmd: ssh-keygen -a 100 -t ed25519 -N '' -f "{{ rsnapshot_ssh_key_file }}"
    creates: "{{ rsnapshot_ssh_key_file }}"

- name: "rsnapshot | create configuration directory"
  file:
    path: /etc/rsnapshot.d
    state: directory

- name: "rsnapshot | copy configuration files"
  copy:
    src: "rsnapshot/{{ item }}"
    dest: "/etc/rsnapshot.d/{{ item }}"
  loop:
    - exclude.inc

- name: "rsnapshot | copy logssh"
  copy:
    src: rsnapshot/logssh.sh
    dest: /usr/local/bin/logssh.sh
    mode: 0666
    when: backup_guest is defined and backup_guest

- name: "rsnapshot | copy cron file"
  copy:
    src: rsnapshot/cron
    dest: /etc/cron.d/rsnapshot