---
- name: "SSH | Copy configuration"
  ansible.builtin.template:
    src: ssh.conf
    dest: "/etc/ssh/sshd_config.d/{{ ansible_hostname }}.conf"
    mode: 0644
  notify: restart ssh

- name: "SSH | Ignore locale environment"
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: '^AcceptEnv LANG LC_*$'
    state: absent
  notify: restart ssh
