---
monit_mailserver: mail.senselab.org
monit_mailserver_port: 465
monit_notifications_sender: noreply@foodcoops.net
monit_notifications_receiver: monit@app.foodcoops.net

rsnapshot_deb_url: http://ftp.de.debian.org/debian/pool/main/r/rsnapshot/rsnapshot_1.4.3-2_all.deb
rsnapshot_ssh_key_file: /root/.ssh/id_ed25519