---
- name: "mta-sts | Copy file"
  template:
    src: nginx/mta-sts.txt.j2
    dest: /var/www/html/mta-sts.txt

- name: "mta-sts | add domain"
  lineinfile:
    path: /etc/dehydrated/domains.txt
    line: "mta-sts.{{ mail_fqdn }}"
  register: add_domain
  when: "'dehydrated' in ansible_facts.packages"

- name: "mta-sts | create certificate"
  command: dehydrated --cron -g
  when: add_domain.changed

- name: "mta-sts | copy nginx sites"
  template:
    src: nginx/nginx-mta-sts.j2
    dest: "/etc/nginx/sites-available/mta-sts.{{ mail_fqdn }}"

- name: "mta-sts | activate nginx site"
  file:
    src: "/etc/nginx/sites-available/mta-sts.{{ mail_fqdn }}"
    dest: "/etc/nginx/sites-enabled/mta-sts.{{ mail_fqdn }}"
    state: link
  notify: reload nginx