---
- name: "packages | Check packages facts"
  package_facts:
    manager: apt

- name: "packages | Install packages"
  apt:
    pkg:
      - fail2ban
      - opendkim
      - pflogsumm
      - pfqueue
      - postfix
      - postfix-cdb
      - postfix-mta-sts-resolver
      - postfix-pcre
      - unbound
    cache_valid_time: 3600