---
- name: "postfix | add domain"
  lineinfile:
    path: /etc/dehydrated/domains.txt
    line: "{{ mail_mx }}"
  register: add_domain
  when: "'dehydrated' in ansible_facts.packages"

- name: "postfix | create certificate"
  command: dehydrated --cron -g
  when: add_domain.changed

- name: "postfix | Copy master.cf"
  copy:
    src: postfix/master.cf
    dest: /etc/postfix/master.cf
    backup: true
  notify: reload postfix

- name: "postfix | Copy main.cf"
  template:
    src: postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    backup: true
  notify: reload postfix

- name: "postfix | Create conf directory"
  file:
    path: "{{ postfix_conf_dir }}"
    state: directory

- name: "postfix | copy configuration files"
  copy:
    src: "postfix/conf.d/{{ item }}"
    dest: "{{ postfix_conf_dir }}/{{ item }}"
  loop:
    - bogus_mx
    - destination_limit
    - header_checks
    - helo_checks
    - sender_checks

- name: "postfix | copy configuration templates"
  template:
    src: "postfix/conf.d/{{ item.src }}.j2"
    dest: "{{ postfix_conf_dir }}/{{ item.src }}"
    force: "{{ item.force|default(true) }}"
  loop:
    - src: transport_foodsoft
    - src: transport_relay
    - src: virtual_aliases
      force: false

- name: "postfix | copy sasl password file"
  template:
    src: postfix/conf.d/sasl_password.j2
    dest: "{{ postfix_conf_dir }}/{{ postfix_sasl_password_file }}"
    mode: 0600

- name: "postfix | Run postmap"
  command: "postmap {{ item.table|default('cdb') }}:{{ item.file }}"
  args:
    chdir: "{{ postfix_conf_dir }}"
  changed_when: false
  notify: reload postfix
  loop:
    - file: sasl_password
    - file: sender_checks
    - file: virtual_aliases

- name: "postfix | remove original logrotate configuration"
  lineinfile:
    path: /etc/logrotate.d/rsyslog
    regexp: "{{ item }}"
    state: absent
  loop:
    - '^/var/log/mail.info$'
    - '^/var/log/mail.warn$'
    - '^/var/log/mail.err$'
    - '^/var/log/mail.log$'

- name: "postfix | configure logrotate for mail.log"
  blockinfile:
    path: /etc/logrotate.d/rsyslog
    marker_begin: Email logging
    block: |
      /var/log/mail.log
      /var/log/mail.info
      /var/log/mail.warn
      /var/log/mail.err
      {
          rotate 1
          daily
          missingok
          notifempty
          compress
          delaycompress
          sharedscripts
          postrotate
              /usr/lib/rsyslog/rsyslog-rotate
          endscript
      }
    
- name: "postfix | cron job for pflogsumm"
  cron:
    name: Send daily mail server reports
    job: '/usr/sbin/pflogsumm --detail 8 --problems-first --no-no-msg-size --reject-detail 12 /var/log/mail.log.1 | mail -s "Mailserver statistic" mail-log@{{ mail_fqdn }}'
    hour: "06"
    minute: "24"