---
# https://github.com/foodcoops/foodsoft/blob/master/config/schedule.rb

- name: "Cron | Insert ENV variables"
  ansible.builtin.cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    env: true
    user: "{{ foodsoft_user }}"
  loop:
    - name: RAILS_ENV
      job: production
    - name: SECRET_KEY_BASE
      job: "{{ foodsoft_secret_key_base }}"
    - name: REDIS_URL
      job: "{{ foodsoft_redis_url }}"

- name: "Cron | Setup task notifier job"
  ansible.builtin.cron:
    name: Upcoming tasks notifier
    user: "{{ foodsoft_user }}"
    minute: "20"
    hour: "07"
    job: /bin/bash -lc "cd {{ foodsoft_home }} && rbenv exec bundle exec rails multicoops:run TASK=foodsoft:notify_upcoming_tasks --silent"

- name: "Cron | Setup weekly task notifier job"
  ansible.builtin.cron:
    name: Weekly tasks notifier
    user: "{{ foodsoft_user }}"
    minute: "20"
    hour: "07"
    job: /bin/bash -lc "cd {{ foodsoft_home }} && rbenv exec bundle exec rails multicoops:run TASK=foodsoft:notify_users_of_weekly_task --silent"

- name: "Cron | Setup bank transactions job"
  ansible.builtin.cron:
    name: Import and assign bank transactions
    user: "{{ foodsoft_user }}"
    minute: "00"
    hour: "05,18"
    day: "1-5"
    job: /bin/bash -lc "cd {{ foodsoft_home }} && rbenv exec bundle exec rails multicoops:run TASK=foodsoft:import_and_assign_bank_transactions --silent"

- name: "Cron | setup weekly tasks job"
  ansible.builtin.cron:
    name: Create weekly tasks
    user: "{{ foodsoft_user }}"
    minute: "14"
    hour: "07"
    job: /bin/bash -lc "cd {{ foodsoft_home }} && rbenv exec bundle exec rails multicoops:run TASK=foodsoft:create_upcoming_periodic_tasks --silent"

- name: "Cron | Setup finish order job"
  ansible.builtin.cron:
    name: Finish ended orders
    user: "{{ foodsoft_user }}"
    job: /bin/bash -lc "cd {{ foodsoft_home }} && rbenv exec bundle exec rails multicoops:run TASK=foodsoft:finish_ended_orders --silent"
