---
- name: "customizations | check railties version"
  shell:
    cmd: rbenv exec bundle info railties | grep "railties (" | cut -d ' ' -f5 | sed 's/[)(]//g'
    chdir: "{{ foodsoft_home }}"
  become: true
  become_user: "{{ foodsoft_user }}"
  changed_when: false
  register: railties_version

# Copy only if version number matches.
- name: "customizations | copy monkey patch for anon logging"
  copy:
    src: foodsoft/anon_logger.rb
    dest: "{{ foodsoft_home }}/config/initializers/anon_logger.rb"
    owner: "{{ foodsoft_user }}"
    group: "{{ foodsoft_user }}"
  when: railties_version.stdout <= "5.2.6"
  notify: restart foodsoft-web

# https://github.com/foodcoops/foodsoft/pull/923
- name: "customizations | Allow stronger passwords"
  replace:
    path: "{{ foodsoft_home }}/app/models/user.rb"
    regexp: 'validates_length_of :password, :in => 5\.\.25'
    replace: 'validates_length_of :password, :in => 10..50'
  notify: restart foodsoft-web

- name: "customizations | Update demo seeds"
  replace:
    path: "{{ foodsoft_home }}/db/seeds/small.en.seeds.rb"
    regexp: ':password => "secret"'
    replace: ':password => "secret1234"'

- name: "customizations | Update minimal seeds"
  replace:
    path: "{{ foodsoft_home }}/db/seeds/minimal.seeds.rb"
    regexp: ':password => "secret"'
    replace: ':password => "secret1234"'

# https://github.com/foodcoops/foodsoft/pull/921
- name: "customizations | Allow decimal numbers in transaction collections"
  replace:
    path: "{{ foodsoft_home }}/app/views/finance/financial_transactions/_ordergroup.haml"
    regexp: '%td= text_field_tag .financial_transactions\[\]\[amount\]., nil, class: .input-small.'
    replace: "%td= number_field_tag 'financial_transactions[][amount]', nil, class: 'input-small', step: 0.01"
  notify: restart foodsoft-web
