---
- name: "foodcoop | {{ item.name }} | Add database"
  mysql_db:
    name: "{{ item.database }}"
    state: present
    collation: utf8mb4_unicode_520_ci
    encoding: utf8mb4
    login_unix_socket: "{{ mariadb_socket }}"
    login_user: root

- name: "foodcoop | {{ item.name }} | Assign database permissions"
  mysql_user:
    name: "{{ foodsoft_db_user }}"
    password: "{{ vault_foodsoft_db_password }}"
    priv: "{{ item.database }}.*:ALL"
    append_privs: true
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
    login_user: root

# If database schema is already loaded it outputs a version number > 0
- name: "foodcoop | {{ item.name }} | test if database schema is already loaded"
  shell:
    cmd: "rbenv exec rails db:version | grep ^Current | sed 's/^.*: //'"
    chdir: "{{ foodsoft_home }}"
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://127.0.0.1:6379
    SECRET_KEY_BASE: "{{ vault_foodsoft_secret_key_base }}"
    DATABASE_URL: mysql2://{{ foodsoft_db_user }}:{{ vault_foodsoft_db_password }}@localhost/{{ item.database }}
  become: true
  become_user: "{{ foodsoft_user }}"
  register: db_version
  changed_when: false

- name: "database | {{ item.name }} | create schema"
  shell:  
    cmd: "rbenv exec rails db:schema:load"
    chdir: "{{ foodsoft_home }}"
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://127.0.0.1:6379
    SECRET_KEY_BASE: "{{ vault_foodsoft_secret_key_base }}"
    DATABASE_URL: mysql2://{{ foodsoft_db_user }}:{{ vault_foodsoft_db_password }}@localhost/{{ item.database }}
  become: true
  become_user: "{{ foodsoft_user }}"
  when: db_version.stdout == "0"

- name: "database | {{ item.name }} | Run seed.rb"
  shell:
    cmd: "rbenv exec rails db:seed"
    chdir: "{{ foodsoft_home }}"
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://127.0.0.1:6379
    SECRET_KEY_BASE: "{{ vault_foodsoft_secret_key_base }}"
    DATABASE_URL: mysql2://{{ foodsoft_db_user }}:{{ vault_foodsoft_db_password }}@localhost/{{ item.database }}
  become: true
  become_user: "{{ foodsoft_user }}"
  when: db_version.stdout == "0" #db:seed is not idempotent in this case

- name: "foodcoop | {{ item.name }} | Add new foodcoop to configuration file"
  blockinfile:
    path: "{{ foodsoft_home }}/config/app_config.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    block: |
      {{ item.name }}:
        <<: *defaults
        database:
          database: {{ item.database }}
      {% if item.instance_name is defined %}
        instance_name: {{ item.instance_name }}
      {% else %}
        instance_name: {{ item.name }}
      {% endif %}
      {% if item.logout_redirect_url is defined %}
        logout_redirect_url: {{ item.logout_redirect_url}}
      {% endif %}
      {% if item.stop_ordering_under is defined %}
        stop_ordering_under: {{ item.stop_ordering_under }}
      {% endif %}
      {% if item.use_apple_points is defined %}
        use_apple_points: {{ item.use_apple_points }}
      {% endif %}
      {% if item.use_nick is defined %}
        use_nick: {{ item.use_nick }}
      {% endif %}
  notify: restart foodsoft-web
