---
- name: "Packages | check facts"
  ansible.builtin.package_facts:
    manager: apt

- name: "Packages | install packages"
  ansible.builtin.apt:
    pkg:
      - default-libmysqlclient-dev
      - libmagic-dev
      - libxml2-dev
      - libxslt-dev
      - pkg-config
      - rbenv
      - redis
      - yarnpkg
