---
- name: "User | Create group"
  ansible.builtin.group:
    name: "{{ foodsoft_user }}"
    system: true

- name: "User | Create local user account"
  ansible.builtin.user:
    name: "{{ foodsoft_user }}"
    group: "{{ foodsoft_user }}"
    shell: /bin/bash
    password_lock: true
    home: "{{ foodsoft_user_home }}"
    system: true

- name: "User | Ensure bash_aliases exists"
  ansible.builtin.file:
    path: "{{ foodsoft_user_home }}/.bash_aliases"
    state: touch
    mode: "0644"
    owner: "{{ foodsoft_user }}"
    group: "{{ foodsoft_user }}"

- name: "User | Set foodsoftctl alias"
  ansible.builtin.lineinfile:
    path: "{{ foodsoft_user_home }}/.bash_aliases"
    line: alias foodsoftctl="REDIS_URL={{ foodsoft_redis_url }} RAILS_ENV=production SECRET_KEY_BASE={{ foodsoft_secret_key_base }} rbenv exec bundle exec rails"
