---
- name: "Foodcoop | Add database | {{ item.name }}"
  community.mysql.mysql_db:
    name: "{{ item.database }}"
    state: present
    collation: utf8mb4_unicode_520_ci
    encoding: utf8mb4
    login_unix_socket: "{{ mariadb_socket }}"
    login_user: root

- name: "Foodcoop | Assign database permissions | {{ item.name }}"
  ansible.builtin.mysql_user:
    name: "{{ foodsoft_db_user }}"
    password: "{{ foodsoft_db_password }}"
    priv: "{{ item.database }}.*:ALL"
    append_privs: true
    state: present
    login_unix_socket: "{{ mariadb_socket }}"
    login_user: root

# If database schema is already loaded it outputs a version number > 0
- name: "Foodcoop | Test if database schema is already loaded | {{ item.name }}"
  ansible.builtin.shell:
    cmd: "rbenv exec bundle exec rails db:version | grep ^Current | sed 's/^.*: //'"
    chdir: "{{ foodsoft_home }}"
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://127.0.0.1:6379
    SECRET_KEY_BASE: "{{ foodsoft_secret_key_base }}"
    DATABASE_URL: mysql2://{{ foodsoft_db_user }}:{{ foodsoft_db_password }}@localhost/{{ item.database }}
  become: true
  become_user: "{{ foodsoft_user }}"
  register: db_version
  changed_when: false

- name: "Foodcoop | Create database schema | {{ item.name }}"
  ansible.builtin.shell:  
    cmd: "rbenv exec rails db:schema:load"
    chdir: "{{ foodsoft_home }}"
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://127.0.0.1:6379
    SECRET_KEY_BASE: "{{ foodsoft_secret_key_base }}"
    DATABASE_URL: mysql2://{{ foodsoft_db_user }}:{{ foodsoft_db_password }}@localhost/{{ item.database }}
  become: true
  become_user: "{{ foodsoft_user }}"
  when: db_version.stdout == "0"

- name: "Foodcoop | Run seed.rb | {{ item.name }}"
  ansible.builtin.shell:
    cmd: "rbenv exec rails db:seed"
    chdir: "{{ foodsoft_home }}"
  environment:
    RAILS_ENV: production
    REDIS_URL: redis://127.0.0.1:6379
    SECRET_KEY_BASE: "{{ foodsoft_secret_key_base }}"
    DATABASE_URL: mysql2://{{ foodsoft_db_user }}:{{ foodsoft_db_password }}@localhost/{{ item.database }}
  become: true
  become_user: "{{ foodsoft_user }}"
  when: db_version.stdout == "0" # db:seed is not idempotent in this case

- name: "Foodcoop | Add new foodcoop to configuration file | {{ item.name }}"
  ansible.builtin.blockinfile:
    path: "{{ foodsoft_home }}/config/app_config.yml"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.instance }}"
    block: "{{ lookup('ansible.builtin.template', '../roles/foodsoft/templates/foodsoft/config.yml.j2') }}"
  notify: restart foodsoft-web
