---
- name: Foodsoft
  ansible.builtin.import_tasks: foodsoft.yml
  tags: foodsoft

- name: Cron
  ansible.builtin.import_tasks: cron.yml
  tags: cron

- name: Webserver
  ansible.builtin.import_tasks: webserver.yml
  tags: webserver

- name: "Add a new Foodcoop"
  ansible.builtin.include_tasks: foodcoop_add.yml
  args:
    apply:
      tags: foodcoop_add
  tags: never
  loop: "{{ vault_foodcoops }}"

- name: "Delete a Foodcoop"
  ansible.builtin.include_tasks: foodcoop_delete.yml
  args:
    apply:
      tags: foodcoop_delete
  tags: never
  loop: "{{ vault_foodcoops }}"
  when: item.deleted is defined and item.deleted
