---
# https://git.systemausfall.org/julius/sharedlists/src/branch/main/config/schedule.rb

- name: "cron | Insert ENV variables"
  cron:
    name: "{{ item. name }}"
    job: "{{ item.job }}"
    env: true
    user: "{{ sharedlists_user }}"
  loop:
    - name: RAILS_ENV
      job: production
    - name: SECRET_KEY_BASE
      job: "{{ vault_sharedlists_secret_key_base }}"

- name: "cron | install job"
  cron:
    name: Update suppliers
    user: "{{ sharedlists_user }}"
    minute: "14"
    hour: "11,16,20"
    job: /bin/bash -lc "cd {{ sharedlists_home }} && rbenv exec rails sync_ftp_files --silent > /dev/null"

- name: "cron | copy Antakya update script"
  template:
    src: antakya_get_products.sh.j2
    dest: /usr/local/bin/antakya_get_products.sh
    mode: 0755

- name: "cron | copy Antakya filter script"
  copy:
    src: antakya_filter_products
    dest: /usr/local/bin
    mode: 0755

- name: "cron | create Antakya cron job"
  cron:
    name: Update Bio Antakya products
    minute: "01"
    hour: "01"
    weekday: "07"
    job: chronic /usr/local/bin/antakya_get_products.sh
