---
- name: "packages | check facts"
  ansible.builtin.package_facts:
    manager: apt

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=940511
- name: "packages | ensure cmdtest is not installed"
  ansible.builtin.apt:
    name: cmdtest
    state: absent

- name: "packages | install packages"
  ansible.builtin.apt:
    pkg:
      - default-libmysqlclient-dev
      - libxml2-dev
      - libxslt-dev
      - pkg-config
      - rbenv
