---
- name: "packages | check facts"
  package_facts:
    manager: apt

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=940511
- name: "packages | ensure cmdtest is not installed"
  apt:
    name: cmdtest
    state: absent

- name: "packages | install packages"
  apt:
    pkg:
      - default-libmysqlclient-dev
      - libxml2-dev
      - libxslt-dev
      - pkg-config
      - rbenv
      - yarnpkg

- name: "packages | create yarn symlink"
  file:
    src: /usr/bin/yarnpkg
    dest: /usr/local/bin/yarn
    state: link