---
- name: "webserver | add domain"
  lineinfile:
    path: /etc/dehydrated/domains.txt
    line: "{{ sharedlists_domain }}"
  register: add_domain
  when: "'dehydrated' in ansible_facts.packages"

- name: "webserver | create certificate"
  command: dehydrated --cron -g
  when: add_domain.changed

- name: "webserver | copy nginx sites"
  template:
    src: nginx.j2
    dest: "/etc/nginx/sites-available/{{ sharedlists_domain }}"

- name: "webserver | activate nginx site"
  file:
    src: "/etc/nginx/sites-available/{{ sharedlists_domain }}"
    dest: "/etc/nginx/sites-enabled/{{ sharedlists_domain }}"
    state: link