---
- name: reload monit
  service:
    name: monit
    state: reloaded
  
- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart foodsoft-web
  systemd:
    name: "{{ foodsoft_web_service }}"
    daemon_reload: true
    state: restarted

- name: restart foodsoft-web-socket
  systemd:
    name: "{{ foodsoft_web_socket }}"
    daemon_reload: true
    state: restarted

- name: restart foodsoft-smtp
  systemd:
    name: "{{ foodsoft_smtp_service }}"
    daemon_reload: true
    state: restarted

- name: restart foodsoft-resque
  systemd:
    name: "{{ foodsoft_resque_service }}"
    daemon_reload: true
    state: restarted
