---
- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: reload monit
  service:
    name: monit
    state: reloaded
