---
- name: Playbook to configure a Foodsoft installation
  hosts:
    - focone
  vars_files: "../galaxy/foodcoops.foodsoft/defaults/main.yml"
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: "../galaxy/foodcoops.foodsoft/handlers/main.yml"
  roles:
    - role: configure-foodsoft
