---
- name: Playbook to configure a Foodsoft installation
  hosts:
    - focone
  vars_files: ../roles/foodsoft/defaults/main.yml
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: ../roles/foodsoft/handlers/main.yml
  roles:
    - role: configure-foodsoft
