---
- name: Playbook to configure a Foodsoft installation
  hosts:
    - focone
  vars_files: "{{ roles_path }}/foodcoops.foodsoft/defaults/main.yml"
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: "{{ roles_path  }}/foodcoops.foodsoft/handlers/main.yml"
  roles:
    - role: configure-foodsoft
