---
- name: Playbook to install a Foodsoft staging instance
  hosts:
    - focone
  roles:
    - role: galaxy/foodsoft
      foodsoft_git_url: https://github.com/kidhab/foodsoft.git
      foodsoft_version: staging
      foodsoft_user: _staging
      foodsoft_home: /opt/foodsoft-staging
      foodsoft_db: foodsoft-staging
      foodsoft_db_user: foodsoft-staging
      foodsoft_db_password: "{{ lookup('password', '/tmp/foodsoft_staging_database_pwd length=42 chars=ascii_letters,digits') }}"
      foodsoft_environment_file: /etc/foodsoft/foodsoft-staging.conf
      foodsoft_web_service: foodsoft-staging-web.service
      foodsoft_web_socket: foodsoft-staging-web.socket
      foodsoft_secret_key_base: "{{ lookup('password', '/tmp/foodsoft_staging_secret_key_base_pwd length=42 chars=ascii_letters,digits') }}"
      foodsoft_smtp_service: foodsoft-staging-smtp.service
      foodsoft_smtp_server_port: "2528"
      foodsoft_resque_service: foodsoft-staging-resque.service
      foodsoft_web_port: "3003"
