---
- name: Playbook to install a Foodsoft demo instance
  hosts:
    - focone
  tasks:
    - name: Include vars for Foodsoft configuration
      ansible.builtin.include_vars:
        file: ../host_vars/focone/foodsoft/app_config_demo.yml
  roles:
    - role: galaxy/foodsoft
      foodsoft_user: _demo
      foodsoft_home: /opt/foodsoft-demo
      foodsoft_db: foodsoft-demo
      foodsoft_db_user: foodsoft-demo
      foodsoft_db_password: "{{ lookup('password', '/tmp/foodsoft_demo_database_pwd length=42 chars=ascii_letters,digits') }}"
      foodsoft_environment_file: /etc/foodsoft/foodsoft-demo.conf
      foodsoft_web_service: foodsoft-demo-web.service
      foodsoft_web_socket: foodsoft-demo-web.socket
      foodsoft_secret_key_base: "{{ lookup('password', '/tmp/foodsoft_demo_secret_key_base_pwd length=42 chars=ascii_letters,digits') }}"
      foodsoft_smtp_service: foodsoft-demo-smtp.service
      foodsoft_smtp_server_port: "2527"
      foodsoft_redis_url: redis://127.0.0.1:6379/2
      foodsoft_resque_service: foodsoft-demo-resque.service
      foodsoft_web_port: "3002"
      monit_foodsoft_config_file: foodsoft-demo
