---
- name: "Webserver | Add domain"
  ansible.builtin.lineinfile:
    path: /etc/dehydrated/domains.txt
    line: "{{ sharedlists_domain }}"
  register: add_domain
  when: "'dehydrated' in ansible_facts.packages"
  notify: Get certificate

- name: "Webserver | Copy NGINX site"
  ansible.builtin.template:
    src: nginx.j2
    dest: "/etc/nginx/sites-available/{{ sharedlists_domain }}"
    mode: "0644"

- name: "Webserver | Enable NGINX site"
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ sharedlists_domain }}"
    dest: "/etc/nginx/sites-enabled/{{ sharedlists_domain }}"
    state: link
