---
- name: "dehydrated | copy renew hook"
  copy:
    src: renew-hook.sh
    dest: /etc/dehydrated/renew-hook.sh
    mode: 0755

- name: "dehydrated | set renew hook path"
  lineinfile:
    path: /etc/dehydrated/config
    line: HOOK=/etc/dehydrated/renew-hook.sh

- name: "dehydrated | create domains file"
  file:
    path: /etc/dehydrated/domains.txt
    state: touch
  changed_when: false

- name: "dehydrated | create cron job"
  cron:
    name: 'Ansible: renew certificates'
    minute: "23"
    hour: "04"
    job: chronic dehydrated --cron -g

- name: "dehydrated | accept terms"
  command:
    cmd: /usr/bin/dehydrated --register --accept-terms
    creates: /var/lib/dehydrated/accounts