---
- name: "nginx | copy main configurationdeacticate access logging"
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: "nginx | copy configuration to conf.d"
  copy:
    src: "conf.d/{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
  loop:
    - request_limits.conf
    - reverse_proxy.conf
    - ssl.conf
  notify: reload nginx

- name: "nginx | copy configuration to snippets"
  copy:
    src: "snippets/{{ item }}"
    dest: "/etc/nginx/snippets/{{ item }}"
  loop:
    - add_headers.conf
    - letsencrypt.conf
  notify: reload nginx

- name: "nginx | create dhparam"
  openssl_dhparam:
    path: "{{ dhparam_global_file }}"
    size: 4096

- name: "nginx | Copy fail2ban configuration files"
  copy:
    src: "fail2ban/{{ item }}"
    dest: "/etc/fail2ban/{{ item }}"
  loop:
    - filter.d/nginx-req-limit.conf
    - jail.d/nginx-req-limit.conf
  when: "'fail2ban' in ansible_facts.packages"
  notify: reload fail2ban

- name: "nginx | Copy cron job to purge IP addresses"
  copy:
    src: nginx-purge-ip
    dest: /etc/cron.daily/nginx-purge-ip
    mode: 0755