---
- name: Get certificate
  ansible.builtin.command: dehydrated --cron -g

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart sharedlists_web
  systemd:
    name: "{{ sharedlists_web_service }}"
    daemon_reload: true
    state: restarted
